export { Header } from './Header';
export { Hero } from './Hero';
export { Footer } from './Footer';
export { default as ContactForm } from './ContactForm';
export { default as Newsletter } from './Newsletter';
export { default as Pricing } from './Pricing';
export { default as Testimonials } from './Testimonials';
export { default as FAQ } from './FAQ';
export { default as Statistics } from './Statistics';
export { default as Navigation } from './Navigation';
export { default as Sidebar } from './Sidebar';
export { default as Dashboard } from './Dashboard';

export type { HeaderProps } from './Header';
export type { HeroProps } from './Hero';
export type { FooterProps } from './Footer';
export type { ContactFormProps, ContactFormData, ContactInfo, ServiceOption } from './ContactForm';
export type { NewsletterProps } from './Newsletter';
export type { PricingProps, PricingPlan } from './Pricing';
export type { TestimonialsProps, Testimonial } from './Testimonials';
export type { FAQProps, FAQItem } from './FAQ';
export type { StatisticsProps, Statistic } from './Statistics';
export type { NavigationProps, NavigationItem } from './Navigation';
export type { SidebarProps, SidebarItem } from './Sidebar';
export type { DashboardProps, DashboardWidget } from './Dashboard';
